### ISSUE TITLE
Error in node_modules/@elderbyte/ngx-stomp/ngx-stomp.d.ts, found version 4, expected 3

### ISSUE THREAD

**Issue by mSenussi** [ElderByte-/ngx-stomp#4]
Hi, 
i'm using ngx-stomp:^5.0.0-beta with angular:4 and angualr-cli:1.4.4
while npm start i got this error:

`ERROR in Error: Metadata version mismatch for module /src/main/webapp/node_modules/@elderbyte/ngx-stomp/ngx-stomp.d.ts, found version 4, expected 3, resolving symbol AppModule in /Users/senussi/Workspace/projects/ow/vr/mirror-frontend/src/main/webapp/src/app/app.module.ts, resolving symbol AppModule in /Users/senussi/Workspace/projects/ow/vr/mirror-frontend/src/main/webapp/src/app/app.module.ts, resolving symbol AppModule in /Users/senussi/Workspace/projects/ow/vr/mirror-frontend/src/main/webapp/src/app/app.module.ts
    at syntaxError (/Users/senussi/Workspace/projects/ow/vr/mirror-frontend/src/main/webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/Users/senussi/Workspace/projects/ow/vr/mirror-frontend/src/main/webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:25118:23)
    at StaticReflector.simplify (/Users/senussi/Workspace/projects/ow/vr/mirror-frontend/src/main/webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:25130:13)
    at StaticReflector.annotations (/Users/senussi/Workspace/projects/ow/vr/mirror-frontend/src/main/webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:24558:41)
    at _getNgModuleMetadata (/Users/senussi/Workspace/projects/ow/vr/mirror-frontend/src/main/webapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/Users/senussi/Workspace/projects/ow/vr/mirror-frontend/src/main/webapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/Users/senussi/Workspace/projects/ow/vr/mirror-frontend/src/main/webapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/senussi/Workspace/projects/ow/vr/mirror-frontend/src/main/webapp/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Users/senussi/Workspace/projects/ow/vr/mirror-frontend/src/main/webapp/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Users/senussi/Workspace/projects/ow/vr/mirror-frontend/src/main/webapp/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at <anonymous>
`

**Comment by n0daft** [comment]
Try updating all angular related packages to latest version (5.0.x)

```
    "@angular/animations": "^5.0.3",
    "@angular/cdk": "^5.0.1",
    "@angular/common": "^5.0.3",
    "@angular/compiler": "^5.0.3",
    "@angular/core": "^5.0.3",
    "@angular/flex-layout": "^2.0.0-beta.10",
    "@angular/forms": "^5.0.3",
    "@angular/material": "^5.0.1",
    "@angular/platform-browser": "^5.0.3",
    "@angular/platform-browser-dynamic": "^5.0.3",
    "@angular/platform-server": "^5.0.3",
    "@angular/router": "^5.0.3",
    ...
```
We are currently using angular version 5 and angular cli `^1.6.1`,
Flex-layout hasn't yet been updated to version 5 but seems to work in version `"^2.0.0-beta.10"`
